"""Asset-related routes — upload, assign, clear, regenerate sheet."""

from __future__ import annotations

import asyncio
import json
import os
import shutil
import signal
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Depends, File, Form, HTTPException, UploadFile
from fastapi.responses import JSONResponse

from dashboard.deps import DashboardContext, get_dashboard_context
from dashboard.helpers.asset_utils import (
    _build_assets_dir_entry,
    _normalize_asset_category,
    _sanitize_asset_name,
    _save_uploaded_asset_file,
)
from dashboard.helpers.checkpoint import _get_run_and_checkpoint, _normalize_storyboard_entity_descriptions
from dashboard.helpers.project import _resolve_storyboard
from dashboard.job_access import list_video_jobs_for_user
from dashboard.persistence import _probe_video_duration_seconds, _save_video_jobs
from dashboard.watchers import _broadcast_video_jobs, broadcast_snapshot_for_matching_run
from dashboard.workspace import resolve_asset_path, resolve_run_path, resolve_storyboard_path, resolve_upload_path
from dashboard.state import video_process_registry

router = APIRouter(tags=["assets"])

# Track which entities are currently being regenerated by the dashboard itself
# (not by the agent process). Key: "{run_dir}:{charsheet_key}" e.g. "/path/to/run:char:陆瑶"
_active_dashboard_regen: set[str] = set()

def _json_http_error(exc: HTTPException) -> JSONResponse:
    return JSONResponse(status_code=exc.status_code, content={"error": exc.detail})



def _stored_path(base_dir: Path, path: Path) -> str:
    try:
        return str(path.resolve().relative_to(base_dir.resolve()))
    except Exception:
        return str(path)


@router.post("/api/upload-source")
async def api_upload_source(file: UploadFile = File(...), ctx: DashboardContext = Depends(get_dashboard_context)):
    """Upload a novel text file or video file for creation mode."""
    ctx.workspace.uploads_dir.mkdir(parents=True, exist_ok=True)
    dest = ctx.workspace.uploads_dir / (file.filename or "upload.bin")
    with open(dest, "wb") as f:
        content = await file.read()
        f.write(content)

    duration_seconds = None
    content_type = (file.content_type or "").lower()
    if content_type.startswith("video/") or dest.suffix.lower() in {
        ".mp4", ".mov", ".avi", ".webm", ".mpeg", ".mpg", ".flv", ".wmv", ".3gp", ".mkv",
    }:
        duration_seconds = _probe_video_duration_seconds(str(dest))

    return {
        "path": str(dest),
        "filename": file.filename,
        "duration_seconds": round(duration_seconds, 2) if duration_seconds else None,
    }


@router.post("/api/upload-image")
async def api_upload_image(
    file: UploadFile = File(...),
    storyboard_path: str = Form(...),
    target: str = Form(...),
    name: str = Form(...),
    project_name: Optional[str] = Form(default=None),
    run_id: Optional[str] = Form(default=None),
    ctx: DashboardContext = Depends(get_dashboard_context),
):
    """Upload a character/location reference image and update the storyboard JSON.

    If project_name and run_id are provided, the image is also copied into the
    run directory as the canonical charsheet/locsheet/propsheet file, and the
    entity is recorded in checkpoint.user_overridden_sheets so the agent will
    not regenerate it on resume.
    """
    normalized_target = _normalize_asset_category(target)
    if not normalized_target:
        return JSONResponse(status_code=400, content={"error": "Unsupported target type"})

    try:
        dest = await _save_uploaded_asset_file(file, category=normalized_target, name=name, workspace=ctx.workspace)
        sb_abs = resolve_storyboard_path(ctx.workspace, storyboard_path, must_exist=True)
    except ValueError as e:
        return JSONResponse(status_code=400, content={"error": str(e)})
    except HTTPException as exc:
        return _json_http_error(exc)

    with open(sb_abs, "r", encoding="utf-8") as f:
        sb = json.load(f)

    image_rel = _stored_path(ctx.workspace.base_dir, dest)
    updated = False
    collection_key = normalized_target
    for entity in sb.get(collection_key, []):
        if entity.get("name") == name:
            entity["image_path"] = image_rel
            updated = True
            break

    if updated:
        _normalize_storyboard_entity_descriptions(sb)
        with open(sb_abs, "w", encoding="utf-8") as f:
            json.dump(sb, f, ensure_ascii=False, indent=2)

    # ── Sync to run directory if project_name + run_id provided ────────────
    run_image_path: Optional[str] = None
    if project_name and run_id:
        try:
            run_path = resolve_run_path(ctx.workspace, project_name, run_id, must_exist=True)
        except HTTPException:
            run_path = None

        if run_path:
            # Determine canonical filename in run dir
            _prefix_map = {"characters": "charsheet", "locations": "locsheet", "props": "propsheet"}
            prefix = _prefix_map.get(normalized_target, "charsheet")
            sanitized = _sanitize_asset_name(name)
            run_img_path = run_path / f"{prefix}_{sanitized}.png"

            # Copy uploaded file into run directory
            shutil.copy2(str(dest), str(run_img_path))
            run_image_path = str(run_img_path)

            # Update run-local storyboard JSON(s)
            for run_sb_path in run_path.glob("*_storyboard.json"):
                try:
                    with open(run_sb_path, "r", encoding="utf-8") as f:
                        run_sb = json.load(f)
                    for entity in run_sb.get(collection_key, []):
                        if entity.get("name") == name:
                            entity["image_path"] = str(run_img_path)
                            break
                    with open(run_sb_path, "w", encoding="utf-8") as f:
                        json.dump(run_sb, f, ensure_ascii=False, indent=2)
                except Exception:
                    pass

            # Record in checkpoint so agent skips regeneration on resume
            from dashboard.helpers.checkpoint import load_checkpoint, save_checkpoint
            _key_prefix = {"characters": "char", "locations": "loc", "props": "prop"}
            charsheet_key = f"{_key_prefix.get(normalized_target, 'char')}:{name}"
            try:
                cp = load_checkpoint(run_path) or {}
                overridden: list = cp.get("user_overridden_sheets", [])
                if charsheet_key not in overridden:
                    overridden.append(charsheet_key)
                cp["user_overridden_sheets"] = overridden
                # Also clear any stale pending task for this entity
                cp.get("pending_charsheet_tasks", {}).pop(charsheet_key, None)
                save_checkpoint(run_path, cp)
            except Exception:
                pass

            await broadcast_snapshot_for_matching_run(project_name, str(run_path))

    return {
        "ok": updated,
        "image_path": run_image_path or image_rel,
        "storyboard": sb,
        "asset": _build_assets_dir_entry(dest),
    }


def _find_running_video_job_for_run(run_dir: str, user_id: int) -> Optional[tuple[str, dict]]:
    """Find the running video job for the given run_dir, if any."""
    for jid, j in list_video_jobs_for_user(user_id):
        if j.get("run_dir") == run_dir and j.get("status") == "running":
            return jid, j
    return None


async def _stop_running_video_job_for_run(run_dir: str, user_id: int) -> Optional[str]:
    """If there is a running video job for the given run_dir, stop it."""
    found = _find_running_video_job_for_run(run_dir, user_id)
    if not found:
        return None
    jid, j = found
    # ── Set status to "stopped" BEFORE killing the process ──────────
    # This prevents the _monitor_process watcher from racing and
    # marking the job as "crashed" when it sees the process exit.
    from dashboard.state import video_job_manager
    video_job_manager.transition(
        jid,
        from_statuses={"running", "paused"},
        to_status="stopped",
    )
    video_process_registry.pop(jid, None)
    _save_video_jobs(user_id=user_id)

    # ── Now kill the process ────────────────────────────────────────
    pid = j.get("pid")
    if pid:
        try:
            os.kill(pid, signal.SIGTERM)
            await asyncio.sleep(3)
            try:
                os.kill(pid, 0)
                os.kill(pid, signal.SIGKILL)
            except ProcessLookupError:
                pass
        except ProcessLookupError:
            pass
        except Exception:
            pass
    return jid


@router.post("/api/run/{project_name}/{run_id}/regenerate-sheet")
async def api_regenerate_sheet(project_name: str, run_id: str, body: dict, ctx: DashboardContext = Depends(get_dashboard_context)):
    """Regenerate a single character/location/prop reference sheet image.

    If the video job is still in the charsheet phase (no video attempts yet),
    we do NOT kill the running process — instead we generate the image in
    parallel and overwrite the file.  The running agent will pick up the new
    image when it scans disk for existing sheets.

    If the job has already entered the video generation phase, we stop the
    process first (original behaviour) so the new sheet can be used on resume.
    """
    name = (body.get("name") or "").strip()
    description = (body.get("description") or "").strip()
    entity_type = (body.get("type") or "").strip().lower()
    personality = (body.get("personality") or "").strip()

    if not name:
        return JSONResponse(status_code=400, content={"error": "name is required"})
    if not description:
        return JSONResponse(status_code=400, content={"error": "description is required"})
    if entity_type not in ("character", "location", "prop"):
        return JSONResponse(status_code=400, content={"error": "type must be character, location, or prop"})

    run_path, cp, err = _get_run_and_checkpoint(project_name, run_id, workspace=ctx.workspace)
    if err:
        return err

    # ── Conflict detection ────────────────────────────────────────────
    charsheet_key_prefix = {"character": "char", "location": "loc", "prop": "prop"}
    charsheet_key = f"{charsheet_key_prefix[entity_type]}:{name}"
    dashboard_regen_key = f"{run_path}:{charsheet_key}"

    from dashboard.helpers.checkpoint import (
        _is_in_charsheet_phase,
        load_checkpoint as _load_cp,
        save_checkpoint as _save_cp,
    )

    is_agent_running = _find_running_video_job_for_run(str(run_path), ctx.user.id) is not None
    pending_task_id = (cp or {}).get("pending_charsheet_tasks", {}).get(charsheet_key)

    # Case 1: Dashboard itself is already regenerating this entity
    if dashboard_regen_key in _active_dashboard_regen:
        return JSONResponse(status_code=409, content={
            "error": f"「{name}」正在生成中，请等待完成",
            "generating": True,
        })

    # Case 2: Agent is running and this entity has a pending task → block
    if is_agent_running and pending_task_id:
        return JSONResponse(status_code=409, content={
            "error": f"「{name}」正在由主进程生成中，请等待完成",
            "generating": True,
        })

    # Case 3: No agent running but stale pending task exists → clear it
    if not is_agent_running and pending_task_id:
        _cp = _load_cp(run_path) or {}
        _cp.get("pending_charsheet_tasks", {}).pop(charsheet_key, None)
        _save_cp(run_path, _cp)

    # ── Decide whether to kill the running process ──────────────────────
    in_charsheet_phase = _is_in_charsheet_phase(cp)
    stopped_job_id = None

    if is_agent_running and not in_charsheet_phase:
        # Already generating videos — must stop the process first
        stopped_job_id = await _stop_running_video_job_for_run(str(run_path), ctx.user.id)
        if stopped_job_id:
            await _broadcast_video_jobs(user_ids={ctx.user.id})
    # else: charsheet phase — let the agent process keep running;
    #       we generate the image in parallel and overwrite the file.

    # ── Build prompt & output path ──────────────────────────────────────
    from clients import get_image_client
    from tools.image_gen import CHARSHEET_TEMPLATE, LOCATION_SHEET_TEMPLATE, PROP_SHEET_TEMPLATE

    sanitized_name = _sanitize_asset_name(name)
    if entity_type == "location":
        prompt = LOCATION_SHEET_TEMPLATE.format(name=name, description=description)
        out_filename = f"locsheet_{sanitized_name}.png"
    elif entity_type == "prop":
        prompt = PROP_SHEET_TEMPLATE.format(name=name, description=description)
        out_filename = f"propsheet_{sanitized_name}.png"
    else:
        desc_with_personality = description
        if personality:
            desc_with_personality = f"{description}，性格：{personality}"
        prompt = CHARSHEET_TEMPLATE.format(name=name, description=desc_with_personality)
        out_filename = f"charsheet_{sanitized_name}.png"

    out_path = run_path / out_filename
    if out_path.exists():
        out_path.unlink()

    # ── Generate image ──────────────────────────────────────────────────
    _active_dashboard_regen.add(dashboard_regen_key)
    try:
        def _generate():
            from clients import get_image_client
            from dashboard.usage_tracker import usage_context
            client = get_image_client()

            with usage_context(user_id=ctx.user.id, step="image_gen"):
                image_data = client.generate_image(
                    prompt=prompt,
                    aspect_ratio="1:1",
                    image_size="2K",
                    timeout_seconds=480,
                    max_retries=3,
                )
                return image_data

        image_data = await asyncio.get_event_loop().run_in_executor(
            None, _generate
        )

        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "wb") as f:
            f.write(image_data)
    except Exception as e:
        # Clean up pending task on failure
        _active_dashboard_regen.discard(dashboard_regen_key)
        try:
            from dashboard.helpers.checkpoint import load_checkpoint as _load_cp, save_checkpoint as _save_cp
            _cp = _load_cp(run_path) or {}
            pending = _cp.get("pending_charsheet_tasks", {})
            pending.pop(charsheet_key, None)
            _cp["pending_charsheet_tasks"] = pending
            _save_cp(run_path, _cp)
        except Exception:
            pass
        return JSONResponse(status_code=500, content={"error": f"Image generation failed: {e}"})

    _active_dashboard_regen.discard(dashboard_regen_key)

    # ── Update storyboard JSON(s) ───────────────────────────────────────
    image_rel = _stored_path(ctx.workspace.base_dir, out_path)
    sb_path_str = _resolve_storyboard(project_name, run_path, cp, workspace=ctx.workspace)
    storyboard_updated = False
    if sb_path_str:
        try:
            sb_abs = resolve_storyboard_path(ctx.workspace, sb_path_str, must_exist=True)
            with open(sb_abs, "r", encoding="utf-8") as f:
                sb = json.load(f)
            category_key = {"character": "characters", "location": "locations", "prop": "props"}[entity_type]
            for entity in sb.get(category_key, []):
                if entity.get("name") == name:
                    entity["image_path"] = image_rel
                    if description and description != entity.get("description", ""):
                        entity["description"] = description
                    if personality and entity_type == "character":
                        entity["personality"] = personality
                    storyboard_updated = True
                    break
            if storyboard_updated:
                _normalize_storyboard_entity_descriptions(sb)
                with open(sb_abs, "w", encoding="utf-8") as f:
                    json.dump(sb, f, ensure_ascii=False, indent=2)
        except Exception:
            pass

    # ── Also update the run-local storyboard copy if it exists ──────────
    run_sb_candidates = list(run_path.glob("*_storyboard.json"))
    for run_sb_path in run_sb_candidates:
        try:
            with open(run_sb_path, "r", encoding="utf-8") as f:
                run_sb = json.load(f)
            category_key = {"character": "characters", "location": "locations", "prop": "props"}[entity_type]
            for entity in run_sb.get(category_key, []):
                if entity.get("name") == name:
                    entity["image_path"] = str(out_path)
                    if description and description != entity.get("description", ""):
                        entity["description"] = description
                    if personality and entity_type == "character":
                        entity["personality"] = personality
                    break
            with open(run_sb_path, "w", encoding="utf-8") as f:
                json.dump(run_sb, f, ensure_ascii=False, indent=2)
        except Exception:
            pass

    await broadcast_snapshot_for_matching_run(project_name, str(run_path))

    # ── Record in checkpoint so agent skips regeneration on resume ──────
    try:
        from dashboard.helpers.checkpoint import load_checkpoint as _load_cp2, save_checkpoint as _save_cp2
        _cp2 = _load_cp2(run_path) or {}
        overridden: list = _cp2.get("user_overridden_sheets", [])
        if charsheet_key not in overridden:
            overridden.append(charsheet_key)
        _cp2["user_overridden_sheets"] = overridden
        _save_cp2(run_path, _cp2)
    except Exception:
        pass

    return {
        "ok": True,
        "image_path": image_rel,
        "image_url": f"/repo-media/{project_name}/{run_id}/{out_filename}",
        "stopped_job_id": stopped_job_id,
        "storyboard_updated": storyboard_updated,
        "in_charsheet_phase": in_charsheet_phase,
    }


@router.post("/api/assets/upload")
async def api_assets_upload(
    file: UploadFile = File(...),
    name: str = Form(...),
    category: str = Form(...),
    ctx: DashboardContext = Depends(get_dashboard_context),
):
    """Upload an image directly into the user's asset library."""
    normalized_category = _normalize_asset_category(category)
    if not normalized_category:
        return JSONResponse(status_code=400, content={"ok": False, "error": "不支持的素材分类"})

    try:
        dest = await _save_uploaded_asset_file(file, category=normalized_category, name=name, workspace=ctx.workspace)
    except ValueError as e:
        return JSONResponse(status_code=400, content={"ok": False, "error": str(e)})

    return {"ok": True, "asset": _build_assets_dir_entry(dest)}


@router.post("/api/assign-asset")
async def api_assign_asset(body: dict, ctx: DashboardContext = Depends(get_dashboard_context)):
    """Assign an existing asset to a character/location/prop in a storyboard."""
    storyboard_path = body.get("storyboard_path", "")
    target = body.get("target", "")
    name = body.get("name", "")
    asset_path = body.get("asset_path", "")

    if not all([storyboard_path, target, name, asset_path]):
        return JSONResponse(status_code=400, content={"error": "Missing required fields"})

    normalized_target = _normalize_asset_category(target)
    if not normalized_target:
        return JSONResponse(status_code=400, content={"error": "Unsupported target type"})

    try:
        sb_abs = resolve_storyboard_path(ctx.workspace, storyboard_path, must_exist=True)
        ap = resolve_asset_path(ctx.workspace, asset_path, must_exist=True)
    except HTTPException as exc:
        return _json_http_error(exc)

    with open(sb_abs, "r", encoding="utf-8") as f:
        sb = json.load(f)

    image_rel = _stored_path(ctx.workspace.base_dir, ap)
    updated = False
    for entity in sb.get(normalized_target, []):
        if entity.get("name") == name:
            entity["image_path"] = image_rel
            updated = True
            break

    if updated:
        _normalize_storyboard_entity_descriptions(sb)
        with open(sb_abs, "w", encoding="utf-8") as f:
            json.dump(sb, f, ensure_ascii=False, indent=2)

    return {"ok": updated, "image_path": image_rel, "storyboard": sb}


@router.post("/api/clear-entity-image")
async def api_clear_entity_image(body: dict, ctx: DashboardContext = Depends(get_dashboard_context)):
    """Clear the reference image for a character/location/prop in a storyboard."""
    storyboard_path = body.get("storyboard_path", "")
    target = body.get("target", "")
    name = body.get("name", "")

    if not all([storyboard_path, target, name]):
        return JSONResponse(status_code=400, content={"error": "Missing required fields"})

    normalized_target = _normalize_asset_category(target)
    if not normalized_target:
        return JSONResponse(status_code=400, content={"error": "Unsupported target type"})

    try:
        sb_abs = resolve_storyboard_path(ctx.workspace, storyboard_path, must_exist=True)
    except HTTPException as exc:
        return _json_http_error(exc)

    with open(sb_abs, "r", encoding="utf-8") as f:
        sb = json.load(f)

    updated = False
    for entity in sb.get(normalized_target, []):
        if entity.get("name") == name:
            entity.pop("image_path", None)
            updated = True
            break

    if updated:
        _normalize_storyboard_entity_descriptions(sb)
        with open(sb_abs, "w", encoding="utf-8") as f:
            json.dump(sb, f, ensure_ascii=False, indent=2)

    return {"ok": updated, "storyboard": sb}
